Repository ditrit/OGrEE-Core, pull requests merged in 2023-04, with the labels that each got.

#19 fixes getslot without template
  CLI/controllers/commandController.go
Labels: Bug

#20 Organisation alias
  CLI/aststr.go
  CLI/controllers/stateController.go
Labels: enhancement

#2 Replaces .env with config.toml
  .gitignore
  CLI/.gitignore
  CLI/README.md
  CLI/ast.go
  CLI/config/config.go
  CLI/controllers/commandController.go
  CLI/controllers/initController.go
  CLI/controllers/stateController.go
  CLI/go.mod
  CLI/go.sum
  CLI/main.go
  CLI/repl.go
  README.md
Labels: enhancement

#28 Hardcoded and config paths are now relative to the executable file
  CLI/config/config.go
  CLI/controllers/commandController.go
  CLI/controllers/initController.go
  CLI/logger/logger.go
  CLI/utils/util.go
Labels: Bug

#30 [CLI] Parse attributes with dash or underscore
  CLI/lexer.go
  CLI/parser.go
  CLI/parser_test.go
Labels: Bug

#48 Stability fix for init and LSOG
  CLI/controllers/commandController.go
  CLI/controllers/initController.go
  deploy/ogreeBoot.sh
Labels: Bug, enhancement

#49 dbAuthCheck
  API/models/base.go
Labels: Bug, enhancement
